apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: payment-requested
  namespace: rideflow
  labels:
    strimzi.io/cluster: rideflow-kafka
spec:
  topicName: payment.requested
  partitions: 6
  replicas: 1 # 3 for production
  config:
    retention.ms: 604800000 # 7 days
    cleanup.policy: delete
